### ISSUE TITLE
Migration contract not compiling

### ISSUE THREAD

**Issue by david-yan** [oasislabs/oasis-box#20]
I pulled the latest version of `contract-kit`, followed the instructions to get an `oasis-box`, ran `truffle compile`, and got the following error:
```
root@5eae4307e51a:/project/box# truffle compile
Compiling ./contracts/Migrations.sol...

/project/box/contracts/Migrations.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.23;
^----------------------^
Compilation failed. See above.
Truffle v5.0.4 (core: 5.0.4)
Node v10.15.1
```

**Comment by david-yan** [comment]
If I try setting `pragma solidity ^0.5.0;`, I get the following error:

```
Building contracts for Oasis

/project/node_modules/oasis-compile/src/solidity-compile.js:9
      throw new Error('Could not compile contracts:' + err);
      ^

Error: Could not compile contracts:CompileError: /project/contracts/Migrations.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.25+commit.59dbf8f1.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.5.0;
^---------------------^
Compilation failed. See above.
    at truffleCompile.all (/project/node_modules/oasis-compile/src/solidity-compile.js:9:13)
    at compile (/project/node_modules/truffle-compile/index.js:133:12)
    at /project/node_modules/truffle-compile/index.js:353:5
    at findRequiredSources (/project/node_modules/truffle-compile/profiler.js:228:7)
    at /project/node_modules/truffle-compile/profiler.js:240:9
    at /project/node_modules/truffle-compile/profiler.js:335:7
    at /project/node_modules/async/dist/async.js:969:16
    at next (/project/node_modules/async/dist/async.js:5225:18)
    at /project/node_modules/truffle-compile/profiler.js:286:16
    at next (/project/node_modules/async/dist/async.js:5223:28)
    at /project/node_modules/truffle-compile/profiler.js:286:16
    at next (/project/node_modules/async/dist/async.js:5223:28)
    at /project/node_modules/truffle-compile/profiler.js:286:16
    at next (/project/node_modules/async/dist/async.js:5223:28)
    at /project/node_modules/truffle-compile/profiler.js:286:16
    at next (/project/node_modules/async/dist/async.js:5223:28)
    at /project/node_modules/truffle-compile/profiler.js:330:9
    at /project/node_modules/truffle-resolver/index.js:79:5
    at /project/node_modules/async/internal/onlyOnce.js:12:16
    at next (/project/node_modules/async/whilst.js:68:18)
    at /project/node_modules/truffle-resolver/index.js:64:7
    at /project/node_modules/truffle-resolver/fs.js:85:5
Error: Unknown exit code: 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/truffle-oasis/build/webpack:/packages/truffle-external-compile/index.js:120:1)
    at ChildProcess.emit (events.js:194:15)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Truffle v5.0.0 (core: 5.0.0)
Node v10.15.1
```

**Comment by willscott** [comment]
cc @armaniferrante  - do you have thoughts on this?

**Comment by armaniferrante** [comment]
Wild guess, but potentially a change in the underlying truffle-compile. Will take a look.

**Comment by armaniferrante** [comment]
I do not get this problem when truffle unboxing into the latest version of contract kit. Closing. @david-yan please let me know if you run into this again.
